WebApppMvc/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApppMvc.Models
{
    public class Product
    {
        [Key]
        public int IdPorduct { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El campo {0} es Requerido")]
        [MaxLength(100, ErrorMessage = "El campo {0} Debe tener maximo {1} caracteres")]
        public string Name { get; set; }

        [Display(Name = "Valor Unidad")]
        [Required(ErrorMessage = "El campo {0} es Requerido")]
        [DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = false)]
        public decimal UnitValue { get; set; }

        [Display(Name = "Activo")]
        public bool Active { get; set; }
    }
}

WebApppMvc/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using WebApppMvc.Models;
using WebApppMvc.Utilities;

namespace WebApppMvc.Controllers
{
    public class ProductController : Controller
    {
        private static string urlBase = "";
        public ProductController()
        {
            urlBase = WebConfigurationManager.AppSettings["UrlApi"];
        }

        // GET: Product
        public async Task<ActionResult> Index()
        {
            var response = await ApiService.Get<Product>(urlBase, "product");

            if (!response.IsSuccess)
            {
                return View();
            }
           return View(response.Result); ;
        }

        // GET: Product/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return await GetId(id);
        }


        private async Task<ActionResult>  GetId(int id)
        {
            try
            {
                var response = await ApiService.GetId<Product>(urlBase, "product", id);

                if (response.IsSuccess)
                {
                    return View(response.Result);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public async Task<ActionResult> Create(Product product)
        {
            try
            {
                product.Active = true;
                var response = await ApiService.Post<Product>(urlBase, "product", product);

                if (!response.IsSuccess)
                {
                    return View(product);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(product);
            }
        }

        // GET: Product/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return await GetId(id);
        }

        // POST: Product/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(Product product)
        {
            try
            {
                var response = await ApiService.Put<Product>(urlBase, "product", product);

                if (!response.IsSuccess)
                {
                    return View(product);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View(product);
            }
        }


      

    }
}

WebApppMvc/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using WebApppMvc.Models;
using WebApppMvc.Utilities;

namespace WebApppMvc.Controllers
{
    public class SaleController : Controller
    {
        private static string urlBase = "";
        public SaleController()
        {
            urlBase = WebConfigurationManager.AppSettings["UrlApi"];
        }

        // GET: Product
        public async Task<ActionResult> Index()
        {
            var response = await ApiService.Get<Sale>(urlBase, "sale");

            if (!response.IsSuccess)
            {
                return View();
            }
            return View(response.Result); ;
        }


        public async Task<ActionResult> Create(int id)
        {
            var response = await ApiService.GetId<Product>(urlBase, "product", id);

            if (!response.IsSuccess)
            {
                return RedirectToAction("Index");
            }
            var product = (Product)response.Result;
            await CreateListClient();
            var data = new Sale();
            data.IdProduct = id;
            data.UnitValue = product.UnitValue;
            data.NameProduct = product.Name;
            return View(data);
        }

        [HttpPost]
        public async Task<ActionResult> Create(Sale sale)
        {
            var response = await ApiService.Post<Sale>(urlBase, "sale", sale);

            if (!response.IsSuccess)
            {
                await CreateListClient(sale.IdClient);
                return View(sale);
            }

            return RedirectToAction("Index");
        }

        private async Task CreateListProducts(int idSelect = 0)
        {
            var list = await ApiService.Get<Product>(urlBase, "product");
            List<Product> items = (List<Product>)list.Result;
            Session["ListProducts"] = items;
            var listActive  = items.Where(a => a.Active == true).OrderBy(a => a.Name).ToList();
            listActive.Add(new Product { IdPorduct = 0, Name = "[Seleccione un Producto...]" });
            ViewBag.IdProduct = new SelectList(listActive, "IdPorduct", "Name", idSelect);
        }

        private async Task CreateListClient(int idSelect = 0)
        {
            var list = await ApiService.Get<Client>(urlBase, "client");
            List<Client> items = (List<Client>)list.Result;
            var listActive = items.Where(a => a.Active == true).OrderBy(a => a.Name).ToList();
            listActive.Add(new Client { IdClient = 0, Name = "[Seleccione un Cliente...]" });
            ViewBag.IdClient = new SelectList(listActive, "IdClient", "Name", idSelect);
        }


        public async Task<ActionResult> SaleClient(int id)
        {
            var response = await ApiService.GetId<Client>(urlBase, "client", id);

            if (!response.IsSuccess)
            {
                Session.Remove("addProduct");
                return RedirectToAction("Index");
            }

            var client = (Client)response.Result;
            await CreateListProducts();
            var data = new Sale();
            data.IdClient = id;
            data.NameClient = string.Format("{0} {1}", client.Name,client.LastName) ;
            return View(data);
        }

        [HttpPost]
        public async Task<ActionResult> SaleClient(Sale sale)
        {
            
            if (Session["addProduct"] == null)
            {
                List<Sale> sales = new List<Sale>();
                sales.Add(sale);
                Session["addProduct"] = sales;
            }
            else
            {
                List<Sale> sales = (List<Sale>)Session["addProduct"];
                sales.Add(sale);
                Session["addProduct"] = sales;

            }

            await CreateListProducts();
            var data = new Sale();
            ModelState.Clear();
            data.IdClient = sale.IdClient;
            data.NameClient = sale.NameClient;
            return View(data);

        }


        public ActionResult GetProduct(int id)
        {
            var listProdus = (List<Product>)Session["ListProducts"];
            var product = listProdus.Where(a => a.IdPorduct == id).First();
            //return product;
            return Json(product, JsonRequestBehavior.AllowGet);
        }


      
        public async Task<ActionResult> SaveProduts()
        {
            List<Sale> sales = (List<Sale>)Session["addProduct"];

            var response = await ApiService.Post<List<Sale>>(urlBase, "sale/saleClient", sales);

            Session.Remove("addProduct");
            return RedirectToAction("Index");
        }
    }
}

WebApppMvc/Views/Product/Create.cshtml
@model WebApppMvc.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Nuevo Producto</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-danger" })


            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApppMvc/Views/Product/Details.cshtml
@model WebApppMvc.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Detalle del Producto</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitValue)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdPorduct }, new { @class = "btn btn-info " }) 
    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-danger" })

</p>

WebApppMvc/Views/Product/Edit.cshtml
@model WebApppMvc.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Actualizar Producto</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPorduct)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitValue, "", new { @class = "text-danger" })
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-primary" />
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
        
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApppMvc/Views/Product/Index.cshtml
@model IEnumerable<WebApppMvc.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Productos</h2>

<p>
    @Html.ActionLink("Nuevo Producto", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdPorduct)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.IdPorduct)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UnitValue)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Active)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.IdPorduct }, new { @class = "btn btn-info " })
        @Html.ActionLink("Detalle", "Details", new { id = item.IdPorduct }, new { @class = "btn btn-warning" })
        @if (item.Active)
        {
            @Html.ActionLink("Vender", "Create", "Sale", new { id = item.IdPorduct }, new { @class = "btn btn-primary " })
        }
        else
        {
            <btn class="btn btn-primary" disabled>Vender</btn>
        }

    </td>
</tr>
}

</table>